spring.application.name: test-project

spring:
    profiles:
        active: qa
    main:
        banner-mode: "off"

countries:
   servers:
       - dev.default.com
       - foo.default.com

---
spring:
    profiles: qa
    datasource:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:${user.dir}/src/main/resources/test-db-qa.sqlite
    jpa:
#        database: SQLITE
        database-platform: org.hibernate.dialect.SQLiteDialect
        show-sql: true
    hibernate:
#        dialect: org.hibernate.dialect.SQLiteDialect
        ddl-auto: update
        show_sql: true

countries:
   servers:
       - dev.qa.com
       - foo.qa.com
---
spring:
    profiles: prod
    datasource:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:${user.dir}/src/main/resources/test-db-prod.sqlite

countries:
   servers:
       - dev.prod.com
       - foo.prod.com

---
spring:
    profiles: uat

    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:${user.dir}/src/main/resources/db.h2.db

    hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
        show_sql: true

countries:
   servers:
       - dev.prod.com
       - foo.prod.com


