
spring:
    main:
#        banner-mode: "on"
    application:
        name: cruncher
    datasource:
        driverClassName: org.sqlite.JDBC
        url: jdbc:sqlite:test.db
jpa:
#    database-platform: that.custom.SQLiteDialect
    hibernate:
              ddl-auto: update
my:
   servers:
       - dev.bar.com
       - foo.bar.com

---

spring:
    profiles: development
server:
    port: 9001

---

spring:
    profiles: production
server:
    port: 0




